//
// Created by Administrator on 3/23/2018.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_infinite_lamejniapp_lame_MP3Recorder */

#ifndef _Included_MP3Recorder
#define _Included_MP3Recorder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:    com_infinite_lamejniapp_lame
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_infinite_lamejniapp_lame_Lame_init__IIIII
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:    com_infinite_lamejniapp_lame
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_com_infinite_lamejniapp_lame_Lame_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     com_infinite_lamejniapp_lame
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_infinite_lamejniapp_lame_Lame_flush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_infinite_lamejniapp_lame
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_infinite_lamejniapp_lame_Lame_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
